### ISSUE TITLE
[2399] Migration to version 15.0

### ISSUE THREAD

**Issue by yostashiro** [qrtl/mi7-custom#114]
# Procedures to follow

- https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0, and
- https://qrtl.slab.com/posts/git-branching-strategy-qq21y11n

# Modules to migrate

- [ ] account_invoice_validate_send_email
- [ ] auth_block_signup @gamhpang
- [ ] base_data_import @gamhpang
- [ ] base_mail_sender_bcc @gamhpang
- [ ] mail_compose_message_reply_to @gamhpang
- [ ] payment_reconcile_invoice @gamhpang
- [ ] sale_automatic_workflow_propose
- [ ] sale_order_payment_charge_line @gamhpang
- [ ] sale_order_show_price_subtotal @gamhpang
- [ ] stock_carrier_info @gamhpang
- [ ] stock_delivery_result_import
- [ ] stock_history_adj
- [ ] stock_picking_yamato_csv
- [ ] stock_view_adj @kakurai8 
- [ ] website_auth_view_mi7
- [ ] website_sale_affiliate_a8
- [ ] website_update_email_notify

Find the modules from https://github.com/qrtl/mi7-custom/tree/st1.

**Comment by yostashiro** [comment]
@gamhpang Please create a PR per module for https://github.com/qrtl/mi7-custom/tree/15st1.  Despite what I said this morning, please follow the steps described here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch to preserve the history.

**Comment by yostashiro** [comment]
@kakurai8 As we merge PRs upon code review, please check the functions in mi715testx to make sure that things work as expected.

**Comment by gamhpang** [comment]
> @gamhpang Please create a PR per module for https://github.com/qrtl/mi7-custom/tree/15st1. Despite what I said this morning, please follow the steps described here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch to preserve the history.

Sure

**Comment by gamhpang** [comment]
@yostashiro I try to create new PR again. The name is  15.0 mig 5 auth block signup #122. If you have time, please check it.

**Comment by gamhpang** [comment]
@yostashiro I just created new PR for base_data_import module. The name is  15.0 migrate base data import #123. 
I also tested by installing module to my local.

**Comment by gamhpang** [comment]
@yostashiro I just created new PR for base_mail_sender_bcc. The name is  15.0 migrate base mail sender bcc #124.

**Comment by gamhpang** [comment]
@yostashiro I just found out my mistake. After I did pre-commit, I replaced the module with migrated module. So pre-commit formatting doesn't apply. I created PR for another module. Please check it, it is ok or not. The name is  15.0 mig sale order payment charge line #126.
